services:
  sqlite:
    build:
      context: ./sqlite_service
      dockerfile: Dockerfile
    ports:
      - "8191:8191"
    volumes:
      - ./sqlite:/db
    command: [database_filmes.db, "CREATE TABLE IF NOT EXISTS filmes (id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT NOT NULL, ano INTEGER NOT NULL, diretor TEXT NOT NULL);"]
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlite
    ports:
      - "8080:8080"
    volumes:
      - ./sqlite:/data/sqlite_db
    environment:
      SQLITE_URL: sqlite:////data/sqlite_db/database_filmes.db
    command: [sh, -cx, "uvicorn main:app --host 0.0.0.0 --port 8080"]